name = "qbank-exam"
compatibility_date = "2026-05-31"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./dist"
exclude = [
  "node_modules",
  ".git",
  ".github",
  "scratch",
  "temp"
]

[observability]
enabled = true
